name: Publish Static Web App to Azure Blob Storage

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install npm packages
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm install

    - name: Build app
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm run build

    - name: Test app
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm run test:unit

    - name: Create directory for artifacts
      shell: bash
      run: |
        mkdir -p artifacts

    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: artifacts

    # - name: Publish app
    #   uses: Azure/cli@v1.0.0
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       az storage blob upload-batch -s $GITHUB_WORKSPACE/src/WebApp/dist -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}