name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

#    - name: Login to Azure
#      uses: Azure/login@v1
#      env:
#        CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
#      with:
#        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
#        creds: $CREDENTIALS

    - name: Login to Azure
      uses: Azure/cli@v1.0.0
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      with:
        # Azure CLI version to be used to execute the script. If not provided, latest version is used
        azcliversion: latest
        # Specify the script here
        inlineScript: |
          az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET -t $TENANT_ID

    - name: Install npm packages
      shell: bash
      run: npm install

    - name: Build app
      shell: bash
      run: npm run build

    - name: Test app
      shell: bash
      run: npm run test:unit

    - name: Publish app
      uses: Azure/cli@v1.0.0
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      with:
        # Azure CLI version to be used to execute the script. If not provided, latest version is used
        azcliversion: latest
        # Specify the script here
        inlineScript: |
          az storage blob upload-batch -s GITHUB_WORKSPACE/src/WebApp/dist -d \$web --account-name $STORAGE_ACCOUNT_NAME
