name: Publish Static Web App to Azure Blob Storage

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install npm packages
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm install

    - name: Build app
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm run build

    - name: Test app
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/WebApp
        npm run test:unit

    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: src/WebApp/dist

  deploy_to_dev:
    needs: build_and_publish
    runs-on: ubuntu-latest

    steps:
    - name: Download app
      uses: actions/download-artifact@v1
      with:
        name: app
        path: src/WebApp/dist

    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s $GITHUB_WORKSPACE/src/WebApp/dist -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}

  deploy_to_prod:
    needs: deploy_to_dev
    runs-on: ubuntu-latest

    steps:
    - name: Download app
      uses: actions/download-artifact@v1
      with:
        name: app
        path: src/WebApp/dist

    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s $GITHUB_WORKSPACE/src/WebApp/dist -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME_2 }}
